### ISSUE TITLE
calculate_features.py

### ISSUE THREAD

**Issue by damientully** [walkergussler/GREMLIN#1]
Hello,

I hoping that you can be of assistance as I am attempting to run your GREMLIN program and get an error message when running the calculate_features.py script. I am using this on some HCV GHOST data and the fasta headers look like this: C20MA4184_1a.fasta_1_1_1a_4791
 
When I run the calculate_features.py script I get the following:
 
```
C20MA4184_1a 3052
Traceback (most recent call last):
  File "/Users/damientully/Downloads/GREMLIN-master/calculate_features.py", line 1991, in <module>
    main_manual(files,pwd)
  File "/Users/damientully/Downloads/GREMLIN-master/calculate_features.py", line 1979, in main_manual
    main(status_dic,pwd,pwd)
  File "/Users/damientully/Downloads/GREMLIN-master/calculate_features.py", line 1881, in main
    david_var_names,david_var_vals=get_davids_vars(num_seqs,adj_1,only_freqs,dvec,full_file)
  File "/Users/damientully/Downloads/GREMLIN-master/calculate_features.py", line 1225, in get_davids_vars
    links,seqs,adj_1,num_seqs=process_component(only_seqs,only_freqs,major_comp,comps_info,adj,DM)
UnboundLocalError: local variable 'only_seqs' referenced before assignment
```
Any assistance with this would be great!
Thanks,
Damien

**Comment by walkergussler** [comment]
Hello Damien!

I'm sorry to be so slow to respond to your comment. I am also sorry that my code is in such a sad state to give an UnboundLocalError this way haha. Are you on Yury/David's team? Are you still interested in utilizing this repository?
